In [1]:
import os
os.environ["NBLAB_PATH"]

'/home/miguel/repos/nblab/'

In [2]:
import scipy.io as sio
import os

# 1. Cargar el archivo .mat 
nblab_path = os.environ["NBLAB_PATH"]
ruta_archivo = f"{nblab_path}Beams/beam_data/perfiles_prueba.mat"
datos_mat = sio.loadmat(ruta_archivo)

# 2. Explorar el contenido
print("--- Claves (Variables) en el archivo ---")
# Filtramos las claves que empiezan con '__' porque son metadatos de MATLAB
variables = [clave for clave in datos_mat.keys() if not clave.startswith('__')]
print(variables)

# 3. Acceder a una variable esio
# Sustituye 'nombre_variable' por una de las claves que se imprimieron en el paso anterior
if 'nombre_variable' in datos_mat:
    mi_variable = datos_mat['nombre_variable']
    print("\n--- Detalles de la variable ---")
    print("Tipo de dato:", type(mi_variable))
    print("Forma (shape):", mi_variable.shape)
    print("Contenido:", mi_variable)

--- Claves (Variables) en el archivo ---
['v1', 'v10', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9']


In [3]:
# Lista de tus variables (puedes ordenarlas numéricamente si prefieres)
variables_interes = ['v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'v10']

print(f"{'Variable':<10} | {'Tipo de Objeto':<25} | {'Dimensiones (Shape)':<20} | {'Tipo de Dato (Dtype)':<15}")
print("-" * 78)

for var in variables_interes:
    if var in datos_mat:
        arreglo = datos_mat[var]
        
        # Conseguir shape y dtype si es un arreglo de numpy
        shape = arreglo.shape if hasattr(arreglo, 'shape') else 'N/A'
        dtype = arreglo.dtype if hasattr(arreglo, 'dtype') else 'N/A'
        tipo_obj = type(arreglo).__name__
        
        print(f"{var:<10} | {tipo_obj:<25} | {str(shape):<20} | {str(dtype):<15}")

Variable   | Tipo de Objeto            | Dimensiones (Shape)  | Tipo de Dato (Dtype)
------------------------------------------------------------------------------
v1         | ndarray                   | (256, 256)           | float64        
v2         | ndarray                   | (256, 256)           | float64        
v3         | ndarray                   | (256, 256)           | float64        
v4         | ndarray                   | (256, 256)           | float64        
v5         | ndarray                   | (256, 256)           | float64        
v6         | ndarray                   | (256, 256)           | float64        
v7         | ndarray                   | (256, 256)           | float64        
v8         | ndarray                   | (256, 256)           | float64        
v9         | ndarray                   | (256, 256)           | float64        
v10        | ndarray                   | (256, 256)           | float64        


In [5]:
# Ejemplo con v1
v1_limpia = datos_mat['v1'].squeeze()

print("Shape original:", datos_mat['v1'].shape)
print("Shape tras el squeeze:", v1_limpia.shape)
print("Contenido de v1 tras el squeeze:", v1_limpia)

Shape original: (256, 256)
Shape tras el squeeze: (256, 256)
Contenido de v1 tras el squeeze: [[0.40808206 0.54517869 0.66899234 ... 0.77650638 0.66899234 0.54517869]
 [0.40808206 0.54517869 0.66899234 ... 0.77650638 0.66899234 0.54517869]
 [0.40808206 0.54517869 0.66899234 ... 0.77650638 0.66899234 0.54517869]
 ...
 [0.40808206 0.54517869 0.66899234 ... 0.77650638 0.66899234 0.54517869]
 [0.40808206 0.54517869 0.66899234 ... 0.77650638 0.66899234 0.54517869]
 [0.40808206 0.54517869 0.66899234 ... 0.77650638 0.66899234 0.54517869]]


In [6]:
import os
import scipy.io as sp


# RUTAS: Ajusta el nombre de tu archivo original aquí
directorio_salida = os.path.join(nblab_path, "Beams", "beam_data")

# Asegurar que el directorio de salida exista
os.makedirs(directorio_salida, exist_ok=True)

# 1. Cargar el archivo maestro con todas las v's
datos_mat = sp.loadmat(ruta_archivo)

# 2. Iterar sobre las variables v1 a v10
for i in range(1, 11):
    nombre_var_original = f"v{i}"
    
    if nombre_var_original in datos_mat:
        # Extraer la matriz (256, 256)
        matriz = datos_mat[nombre_var_original]
        
        # 3. Definir el nombre del nuevo archivo (ej. beam_v1_256.mat)
        # Puedes cambiar el prefijo "beam_" según lo que espera tu pipeline
        nombre_nuevo_archivo = f"beam_{nombre_var_original}_256.mat"
        ruta_guardado = os.path.join(directorio_salida, nombre_nuevo_archivo)
        
        # 4. Guardar la matriz forzando que la variable interna se llame "Uo"
        sp.savemat(ruta_guardado, {"Uo": matriz})
        
        print(f"✅ Archivo creado: {nombre_nuevo_archivo} | Variable interna: 'Uo'")

✅ Archivo creado: beam_v1_256.mat | Variable interna: 'Uo'
✅ Archivo creado: beam_v2_256.mat | Variable interna: 'Uo'
✅ Archivo creado: beam_v3_256.mat | Variable interna: 'Uo'
✅ Archivo creado: beam_v4_256.mat | Variable interna: 'Uo'
✅ Archivo creado: beam_v5_256.mat | Variable interna: 'Uo'
✅ Archivo creado: beam_v6_256.mat | Variable interna: 'Uo'
✅ Archivo creado: beam_v7_256.mat | Variable interna: 'Uo'
✅ Archivo creado: beam_v8_256.mat | Variable interna: 'Uo'
✅ Archivo creado: beam_v9_256.mat | Variable interna: 'Uo'
✅ Archivo creado: beam_v10_256.mat | Variable interna: 'Uo'


In [7]:
import os
import scipy.io
import matplotlib.pyplot as plt

# Define la ruta principal a tu carpeta de Resultados. 
# Si estás usando la variable de entorno, puedes descomentar la siguiente línea:
# results_dir = os.path.join(os.environ.get("NBLAB_PATH", ""), "Results")
results_dir = os.path.join(nblab_path, "Results")

def generate_and_save_images(base_dir):
    # Iterar sobre todos los elementos en el directorio de resultados
    for folder_name in os.listdir(base_dir):
        folder_path = os.path.join(base_dir, folder_name)
        
        # Asegurarnos de que sea una carpeta y no un archivo suelto
        if not os.path.isdir(folder_path):
            continue
            
        mat_file_path = os.path.join(folder_path, "data.mat")
        
        # Verificar si existe el archivo data.mat en esa carpeta
        if not os.path.exists(mat_file_path):
            print(f"Omitiendo '{folder_name}': No se encontró data.mat")
            continue
            
        try:
            # 1. Cargar el archivo .mat
            mat_data = scipy.io.loadmat(mat_file_path)
            
            # Extraer las matrices (ajusta los nombres si los guardaste diferente)
            pred_beam = mat_data.get('pred_beam')
            true_beam = mat_data.get('true_beam')
            
            if pred_beam is None or true_beam is None:
                print(f"Omitiendo '{folder_name}': Faltan variables en data.mat")
                continue

            # 2. Crear la figura (1 fila, 2 columnas)
            fig, axes = plt.subplots(1, 2, figsize=(10, 5))
            
            # Graficar True Beam
            im1 = axes[0].imshow(true_beam, cmap='viridis', aspect='auto')
            axes[0].set_title('True Beam')
            fig.colorbar(im1, ax=axes[0])
            
            # Graficar Pred Beam
            im2 = axes[1].imshow(pred_beam, cmap='viridis', aspect='auto')
            axes[1].set_title('Predicted Beam')
            fig.colorbar(im2, ax=axes[1])
            
            plt.tight_layout()
            
            # 3. Guardar la figura como JPG dentro del mismo directorio
            jpg_file_path = os.path.join(folder_path, "matrices_plot.jpg")
            plt.savefig(jpg_file_path, format='jpg', dpi=150)
            
            # Cerrar la figura para liberar memoria RAM
            plt.close(fig)
            
            print(f"✅ Imagen guardada exitosamente en: {folder_name}")
            
        except Exception as e:
            print(f"❌ Error procesando {folder_name}: {e}")

# Ejecutar la función
generate_and_save_images(results_dir)

✅ Imagen guardada exitosamente en: beam_v2_256_20_20_30
✅ Imagen guardada exitosamente en: beam_v1_256_20_20_30
✅ Imagen guardada exitosamente en: beam_v9_256_20_40_10
✅ Imagen guardada exitosamente en: beam_v5_256_20_30_100
✅ Imagen guardada exitosamente en: beam_v6_256_20_30_30
✅ Imagen guardada exitosamente en: beam_v3_256_20_25_10
✅ Imagen guardada exitosamente en: beam_v4_256_20_27_10
✅ Imagen guardada exitosamente en: beam_v8_256_20_30_10
